-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


ALTER TABLE IF EXISTS public.alertas_stock DROP CONSTRAINT IF EXISTS alertas_stock_producto_id_fkey;

ALTER TABLE IF EXISTS public.alertas_stock DROP CONSTRAINT IF EXISTS alertas_stock_sucursal_id_fkey;

ALTER TABLE IF EXISTS public.detalles_devolucion_solicitud DROP CONSTRAINT IF EXISTS detalles_devolucion_solicitud_producto_id_fkey;

ALTER TABLE IF EXISTS public.detalles_devolucion_solicitud DROP CONSTRAINT IF EXISTS detalles_devolucion_solicitud_solicitud_id_fkey;

ALTER TABLE IF EXISTS public.detalles_orden_compra DROP CONSTRAINT IF EXISTS detalles_orden_compra_orden_id_fkey;

ALTER TABLE IF EXISTS public.detalles_orden_compra DROP CONSTRAINT IF EXISTS detalles_orden_compra_producto_id_fkey;

ALTER TABLE IF EXISTS public.detalles_transferencia DROP CONSTRAINT IF EXISTS detalles_transferencia_producto_id_fkey;

ALTER TABLE IF EXISTS public.detalles_transferencia DROP CONSTRAINT IF EXISTS detalles_transferencia_transferencia_id_fkey;

ALTER TABLE IF EXISTS public.detalles_venta DROP CONSTRAINT IF EXISTS detalles_venta_producto_id_fkey;

ALTER TABLE IF EXISTS public.detalles_venta DROP CONSTRAINT IF EXISTS detalles_venta_venta_id_fkey;

ALTER TABLE IF EXISTS public.inventario_local DROP CONSTRAINT IF EXISTS inventario_local_producto_id_fkey;

ALTER TABLE IF EXISTS public.inventario_local DROP CONSTRAINT IF EXISTS inventario_local_sucursal_id_fkey;

ALTER TABLE IF EXISTS public.movimiento_inventario DROP CONSTRAINT IF EXISTS movimiento_inventario_producto_id_fkey;

ALTER TABLE IF EXISTS public.movimiento_inventario DROP CONSTRAINT IF EXISTS movimiento_inventario_sucursal_id_fkey;

ALTER TABLE IF EXISTS public.movimiento_inventario DROP CONSTRAINT IF EXISTS movimiento_inventario_usuario_id_fkey;

ALTER TABLE IF EXISTS public.ordenes_compra DROP CONSTRAINT IF EXISTS ordenes_compra_proveedor_id_fkey;

ALTER TABLE IF EXISTS public.ordenes_compra DROP CONSTRAINT IF EXISTS ordenes_compra_resuelto_por_id_fkey;

ALTER TABLE IF EXISTS public.ordenes_compra DROP CONSTRAINT IF EXISTS ordenes_compra_sucursal_id_fkey;

ALTER TABLE IF EXISTS public.ordenes_compra DROP CONSTRAINT IF EXISTS ordenes_compra_usuario_id_fkey;

ALTER TABLE IF EXISTS public.ordenes_compra DROP CONSTRAINT IF EXISTS ordenes_compra_usuario_recepcion_id_fkey;

ALTER TABLE IF EXISTS public.precio_por_lista DROP CONSTRAINT IF EXISTS precio_por_lista_lista_id_fkey;

ALTER TABLE IF EXISTS public.precio_por_lista DROP CONSTRAINT IF EXISTS precio_por_lista_producto_id_fkey;

ALTER TABLE IF EXISTS public.producto DROP CONSTRAINT IF EXISTS fk_producto_unidad_medida;

ALTER TABLE IF EXISTS public.producto_proveedor DROP CONSTRAINT IF EXISTS producto_proveedor_producto_id_fkey;

ALTER TABLE IF EXISTS public.producto_proveedor DROP CONSTRAINT IF EXISTS producto_proveedor_proveedor_id_fkey;

ALTER TABLE IF EXISTS public.producto_unidad DROP CONSTRAINT IF EXISTS producto_unidad_producto_id_fkey;

ALTER TABLE IF EXISTS public.producto_unidad DROP CONSTRAINT IF EXISTS producto_unidad_unidad_id_fkey;

ALTER TABLE IF EXISTS public.rutas_logisticas DROP CONSTRAINT IF EXISTS rutas_logisticas_sucursal_destino_id_fkey;

ALTER TABLE IF EXISTS public.rutas_logisticas DROP CONSTRAINT IF EXISTS rutas_logisticas_sucursal_origen_id_fkey;

ALTER TABLE IF EXISTS public.solicitudes_devolucion DROP CONSTRAINT IF EXISTS solicitudes_devolucion_aprobador_id_fkey;

ALTER TABLE IF EXISTS public.solicitudes_devolucion DROP CONSTRAINT IF EXISTS solicitudes_devolucion_solicitante_id_fkey;

ALTER TABLE IF EXISTS public.solicitudes_devolucion DROP CONSTRAINT IF EXISTS solicitudes_devolucion_sucursal_id_fkey;

ALTER TABLE IF EXISTS public.solicitudes_devolucion DROP CONSTRAINT IF EXISTS solicitudes_devolucion_venta_id_fkey;

ALTER TABLE IF EXISTS public.transferencias DROP CONSTRAINT IF EXISTS transferencias_parent_transfer_id_fkey;

ALTER TABLE IF EXISTS public.transferencias DROP CONSTRAINT IF EXISTS transferencias_resuelto_por_id_fkey;

ALTER TABLE IF EXISTS public.transferencias DROP CONSTRAINT IF EXISTS transferencias_sucursal_destino_id_fkey;

ALTER TABLE IF EXISTS public.transferencias DROP CONSTRAINT IF EXISTS transferencias_sucursal_origen_id_fkey;

ALTER TABLE IF EXISTS public.usuario DROP CONSTRAINT IF EXISTS usuario_rol_id_fkey;

ALTER TABLE IF EXISTS public.usuario DROP CONSTRAINT IF EXISTS usuario_sucursal_id_fkey;

ALTER TABLE IF EXISTS public.ventas DROP CONSTRAINT IF EXISTS ventas_sucursal_id_fkey;

ALTER TABLE IF EXISTS public.ventas DROP CONSTRAINT IF EXISTS ventas_usuario_id_fkey;



DROP TABLE IF EXISTS public.alertas_stock;

CREATE TABLE IF NOT EXISTS public.alertas_stock
(
    id bigserial NOT NULL,
    sucursal_id bigint NOT NULL,
    producto_id bigint NOT NULL,
    mensaje text COLLATE pg_catalog."default" NOT NULL,
    fecha_alerta timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resuelta boolean NOT NULL DEFAULT false,
    tipo_resolucion character varying(50) COLLATE pg_catalog."default",
    referencia_id bigint,
    motivo_descarte text COLLATE pg_catalog."default",
    fecha_resolucion timestamp without time zone,
    tipo_alerta character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT alertas_stock_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.detalles_devolucion_solicitud;

CREATE TABLE IF NOT EXISTS public.detalles_devolucion_solicitud
(
    id bigserial NOT NULL,
    solicitud_id bigint NOT NULL,
    producto_id bigint NOT NULL,
    cantidad integer NOT NULL,
    motivo_especifico text COLLATE pg_catalog."default",
    precio_unidad_venta numeric(12, 2) NOT NULL,
    CONSTRAINT detalles_devolucion_solicitud_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.detalles_orden_compra;

CREATE TABLE IF NOT EXISTS public.detalles_orden_compra
(
    id bigserial NOT NULL,
    orden_id bigint NOT NULL,
    producto_id bigint NOT NULL,
    cantidad numeric(12, 4) NOT NULL,
    precio_unitario_pactado numeric(12, 2) NOT NULL,
    subtotal numeric(12, 2) NOT NULL,
    descuento_pct numeric(5, 2) NOT NULL DEFAULT 0.00,
    cantidad_recibida numeric(12, 4) DEFAULT 0.0,
    CONSTRAINT detalles_orden_compra_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.detalles_transferencia;

CREATE TABLE IF NOT EXISTS public.detalles_transferencia
(
    id bigserial NOT NULL,
    transferencia_id bigint NOT NULL,
    producto_id bigint NOT NULL,
    cantidad_solicitada integer NOT NULL,
    cantidad_enviada integer NOT NULL DEFAULT 0,
    cantidad_recibida integer NOT NULL DEFAULT 0,
    faltantes integer NOT NULL DEFAULT 0,
    producto_nombre character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT detalles_transferencia_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.detalles_venta;

CREATE TABLE IF NOT EXISTS public.detalles_venta
(
    id bigserial NOT NULL,
    venta_id bigint NOT NULL,
    producto_id bigint NOT NULL,
    cantidad integer NOT NULL,
    precio_unitario_aplicado numeric(12, 2) NOT NULL,
    porcentaje_descuento numeric(5, 2) NOT NULL DEFAULT 0.00,
    subtotal_linea numeric(12, 2) NOT NULL,
    producto_nombre character varying(200) COLLATE pg_catalog."default",
    CONSTRAINT detalles_venta_pkey PRIMARY KEY (id)
);


DROP TABLE IF EXISTS public.inventario_local;

CREATE TABLE IF NOT EXISTS public.inventario_local
(
    id bigserial NOT NULL,
    sucursal_id bigint NOT NULL,
    producto_id bigint NOT NULL,
    cantidad_actual numeric(12, 4) DEFAULT 0.0,
    stock_minimo numeric(12, 4) DEFAULT 0.0,
    last_updated timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    stock_comprometido numeric(12, 4) DEFAULT 0.0,
    CONSTRAINT inventario_local_pkey PRIMARY KEY (id),
    CONSTRAINT inventario_local_sucursal_id_producto_id_key UNIQUE (sucursal_id, producto_id)
);

COMMENT ON COLUMN public.inventario_local.stock_comprometido
    IS 'Mercancía reservada por traslados pendientes que aún no han sido despachados físicamente.';

DROP TABLE IF EXISTS public.lista_precios;

CREATE TABLE IF NOT EXISTS public.lista_precios
(
    id bigserial NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    descripcion character varying(255) COLLATE pg_catalog."default",
    activa boolean NOT NULL DEFAULT true,
    CONSTRAINT lista_precios_pkey PRIMARY KEY (id),
    CONSTRAINT lista_precios_nombre_key UNIQUE (nombre)
);

DROP TABLE IF EXISTS public.movimiento_inventario;

CREATE TABLE IF NOT EXISTS public.movimiento_inventario
(
    id bigserial NOT NULL,
    tipo character varying(20) COLLATE pg_catalog."default" NOT NULL,
    motivo character varying(50) COLLATE pg_catalog."default" NOT NULL,
    cantidad numeric(12, 4) NOT NULL,
    fecha timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    producto_id bigint NOT NULL,
    sucursal_id bigint NOT NULL,
    usuario_id bigint NOT NULL,
    referencia_id bigint,
    tipo_referencia character varying(50) COLLATE pg_catalog."default",
    saldo_final numeric(12, 2) DEFAULT 0,
    observaciones character varying(255) COLLATE pg_catalog."default",
    sub_motivo character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT movimiento_inventario_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.ordenes_compra;

CREATE TABLE IF NOT EXISTS public.ordenes_compra
(
    id bigserial NOT NULL,
    proveedor_id bigint NOT NULL,
    sucursal_id bigint NOT NULL,
    usuario_id bigint NOT NULL,
    usuario_recepcion_id bigint,
    fecha_solicitud timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_estimada_llegada timestamp without time zone,
    fecha_real_llegada timestamp without time zone,
    estado_recepcion character varying(30) COLLATE pg_catalog."default" NOT NULL DEFAULT 'PENDIENTE'::character varying,
    estado_pago character varying(30) COLLATE pg_catalog."default" NOT NULL DEFAULT 'POR_PAGAR'::character varying,
    total numeric(12, 2) NOT NULL DEFAULT 0.00,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    fecha_vencimiento_pago timestamp without time zone,
    plazo_pago_dias integer NOT NULL DEFAULT 30,
    version integer DEFAULT 0,
    motivo_resolucion text COLLATE pg_catalog."default",
    resuelto_por_id bigint,
    fecha_resolucion timestamp without time zone,
    excepcion_aprobada boolean NOT NULL DEFAULT false,
    tiempo_entrega_dias integer DEFAULT 3,
    CONSTRAINT ordenes_compra_pkey PRIMARY KEY (id)
);

COMMENT ON COLUMN public.ordenes_compra.tiempo_entrega_dias
    IS 'Plazo acordado en días para la entrega del pedido por parte del proveedor.';

DROP TABLE IF EXISTS public.precio_por_lista;

CREATE TABLE IF NOT EXISTS public.precio_por_lista
(
    id bigserial NOT NULL,
    lista_id bigint NOT NULL,
    producto_id bigint NOT NULL,
    precio numeric(12, 2) NOT NULL,
    CONSTRAINT precio_por_lista_pkey PRIMARY KEY (id),
    CONSTRAINT uq_lista_producto UNIQUE (lista_id, producto_id)
);

DROP TABLE IF EXISTS public.producto;

CREATE TABLE IF NOT EXISTS public.producto
(
    id bigserial NOT NULL,
    sku character varying(50) COLLATE pg_catalog."default" NOT NULL,
    nombre character varying(150) COLLATE pg_catalog."default" NOT NULL,
    costo_promedio numeric(12, 2) DEFAULT 0.0,
    precio_venta numeric(12, 2) DEFAULT 0.0,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    unidad_id bigint NOT NULL,
    activa boolean DEFAULT true,
    CONSTRAINT producto_pkey PRIMARY KEY (id),
    CONSTRAINT producto_sku_key UNIQUE (sku)
);

DROP TABLE IF EXISTS public.producto_proveedor;

CREATE TABLE IF NOT EXISTS public.producto_proveedor
(
    id bigserial NOT NULL,
    producto_id bigint NOT NULL,
    proveedor_id bigint NOT NULL,
    sku_proveedor character varying(100) COLLATE pg_catalog."default",
    precio_pactado numeric(12, 2) DEFAULT 0.00,
    tiempo_entrega_dias integer DEFAULT 0,
    preferido boolean DEFAULT false,
    CONSTRAINT producto_proveedor_pkey PRIMARY KEY (id),
    CONSTRAINT producto_proveedor_producto_id_proveedor_id_key UNIQUE (producto_id, proveedor_id)
);

DROP TABLE IF EXISTS public.producto_unidad;

CREATE TABLE IF NOT EXISTS public.producto_unidad
(
    id bigserial NOT NULL,
    producto_id bigint NOT NULL,
    unidad_id bigint NOT NULL,
    factor_conversion numeric(10, 4) DEFAULT 1.0,
    es_base boolean DEFAULT false,
    CONSTRAINT producto_unidad_pkey PRIMARY KEY (id),
    CONSTRAINT producto_unidad_producto_id_unidad_id_key UNIQUE (producto_id, unidad_id)
);

DROP TABLE IF EXISTS public.proveedor;

CREATE TABLE IF NOT EXISTS public.proveedor
(
    id bigserial NOT NULL,
    nombre character varying(150) COLLATE pg_catalog."default" NOT NULL,
    contacto character varying(150) COLLATE pg_catalog."default",
    tiempo_entrega_dias integer DEFAULT 0,
    CONSTRAINT proveedor_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.rol;

CREATE TABLE IF NOT EXISTS public.rol
(
    id bigserial NOT NULL,
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT rol_pkey PRIMARY KEY (id),
    CONSTRAINT rol_nombre_key UNIQUE (nombre)
);

DROP TABLE IF EXISTS public.rutas_logisticas;

CREATE TABLE IF NOT EXISTS public.rutas_logisticas
(
    id bigserial NOT NULL,
    sucursal_origen_id bigint NOT NULL,
    sucursal_destino_id bigint NOT NULL,
    tiempo_estimado_horas integer DEFAULT 0,
    costo_flete_estimado numeric(12, 2) DEFAULT 0.0,
    CONSTRAINT rutas_logisticas_pkey PRIMARY KEY (id),
    CONSTRAINT rutas_logisticas_sucursal_origen_id_sucursal_destino_id_key UNIQUE (sucursal_origen_id, sucursal_destino_id)
);

DROP TABLE IF EXISTS public.solicitudes_devolucion;

CREATE TABLE IF NOT EXISTS public.solicitudes_devolucion
(
    id bigserial NOT NULL,
    venta_id bigint NOT NULL,
    sucursal_id bigint NOT NULL,
    solicitante_id bigint NOT NULL,
    aprobador_id bigint,
    estado character varying(30) COLLATE pg_catalog."default" NOT NULL DEFAULT 'PENDIENTE'::character varying,
    fecha_solicitud timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_procesamiento timestamp without time zone,
    motivo_general text COLLATE pg_catalog."default" NOT NULL,
    comentario_aprobador text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT solicitudes_devolucion_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.sucursal;

CREATE TABLE IF NOT EXISTS public.sucursal
(
    id bigserial NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    direccion character varying(255) COLLATE pg_catalog."default",
    telefono character varying(50) COLLATE pg_catalog."default",
    activa boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT sucursal_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.transferencias;

CREATE TABLE IF NOT EXISTS public.transferencias
(
    id bigserial NOT NULL,
    estado character varying(30) COLLATE pg_catalog."default" NOT NULL,
    fecha_solicitud timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_estimada_llegada timestamp without time zone,
    fecha_real_llegada timestamp without time zone,
    sucursal_origen_id bigint NOT NULL,
    sucursal_destino_id bigint NOT NULL,
    transportista character varying(150) COLLATE pg_catalog."default",
    notas_recepcion text COLLATE pg_catalog."default",
    parent_transfer_id bigint,
    version integer DEFAULT 0,
    motivo_resolucion text COLLATE pg_catalog."default",
    resuelto_por_id bigint,
    fecha_resolucion timestamp without time zone,
    prioridad character varying(20) COLLATE pg_catalog."default" DEFAULT 'NORMAL'::character varying,
    costo_envio numeric(12, 2),
    numero_guia character varying(100) COLLATE pg_catalog."default",
    fecha_despacho timestamp without time zone,
    solicitante_id bigint,
    solicitante_nombre character varying(255) COLLATE pg_catalog."default",
    autorizador_id bigint,
    autorizador_nombre character varying(255) COLLATE pg_catalog."default",
    despachador_id bigint,
    despachador_nombre character varying(255) COLLATE pg_catalog."default",
    recibidor_id bigint,
    recibidor_nombre character varying(255) COLLATE pg_catalog."default",
    resolutor_id bigint,
    resolutor_nombre character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT transferencias_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.unidad_medida;

CREATE TABLE IF NOT EXISTS public.unidad_medida
(
    id bigserial NOT NULL,
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    abreviatura character varying(10) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT unidad_medida_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.usuario;

CREATE TABLE IF NOT EXISTS public.usuario
(
    id bigserial NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email character varying(150) COLLATE pg_catalog."default" NOT NULL,
    password_hash character varying(255) COLLATE pg_catalog."default" NOT NULL,
    rol_id bigint NOT NULL,
    sucursal_id bigint,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    activa boolean DEFAULT true,
    CONSTRAINT usuario_pkey PRIMARY KEY (id),
    CONSTRAINT usuario_email_key UNIQUE (email)
);

DROP TABLE IF EXISTS public.ventas;

CREATE TABLE IF NOT EXISTS public.ventas
(
    id bigserial NOT NULL,
    sucursal_id bigint NOT NULL,
    usuario_id bigint NOT NULL,
    fecha timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    subtotal numeric(12, 2) NOT NULL DEFAULT 0.00,
    descuento_total numeric(12, 2) NOT NULL DEFAULT 0.00,
    total_final numeric(12, 2) NOT NULL DEFAULT 0.00,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    estado character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'COMPLETED'::character varying,
    motivo_anulacion text COLLATE pg_catalog."default",
    cliente_nombre character varying(100) COLLATE pg_catalog."default",
    cliente_documento character varying(20) COLLATE pg_catalog."default",
    sucursal_nombre character varying(100) COLLATE pg_catalog."default",
    vendedor_nombre character varying(100) COLLATE pg_catalog."default",
    global_discount_percentage numeric(5, 2) DEFAULT 0.00,
    CONSTRAINT ventas_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.alertas_stock
    ADD CONSTRAINT alertas_stock_producto_id_fkey FOREIGN KEY (producto_id)
    REFERENCES public.producto (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.alertas_stock
    ADD CONSTRAINT alertas_stock_sucursal_id_fkey FOREIGN KEY (sucursal_id)
    REFERENCES public.sucursal (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.detalles_devolucion_solicitud
    ADD CONSTRAINT detalles_devolucion_solicitud_producto_id_fkey FOREIGN KEY (producto_id)
    REFERENCES public.producto (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.detalles_devolucion_solicitud
    ADD CONSTRAINT detalles_devolucion_solicitud_solicitud_id_fkey FOREIGN KEY (solicitud_id)
    REFERENCES public.solicitudes_devolucion (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.detalles_orden_compra
    ADD CONSTRAINT detalles_orden_compra_orden_id_fkey FOREIGN KEY (orden_id)
    REFERENCES public.ordenes_compra (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.detalles_orden_compra
    ADD CONSTRAINT detalles_orden_compra_producto_id_fkey FOREIGN KEY (producto_id)
    REFERENCES public.producto (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.detalles_transferencia
    ADD CONSTRAINT detalles_transferencia_producto_id_fkey FOREIGN KEY (producto_id)
    REFERENCES public.producto (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.detalles_transferencia
    ADD CONSTRAINT detalles_transferencia_transferencia_id_fkey FOREIGN KEY (transferencia_id)
    REFERENCES public.transferencias (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.detalles_venta
    ADD CONSTRAINT detalles_venta_producto_id_fkey FOREIGN KEY (producto_id)
    REFERENCES public.producto (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.detalles_venta
    ADD CONSTRAINT detalles_venta_venta_id_fkey FOREIGN KEY (venta_id)
    REFERENCES public.ventas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.inventario_local
    ADD CONSTRAINT inventario_local_producto_id_fkey FOREIGN KEY (producto_id)
    REFERENCES public.producto (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.inventario_local
    ADD CONSTRAINT inventario_local_sucursal_id_fkey FOREIGN KEY (sucursal_id)
    REFERENCES public.sucursal (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.movimiento_inventario
    ADD CONSTRAINT movimiento_inventario_producto_id_fkey FOREIGN KEY (producto_id)
    REFERENCES public.producto (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.movimiento_inventario
    ADD CONSTRAINT movimiento_inventario_sucursal_id_fkey FOREIGN KEY (sucursal_id)
    REFERENCES public.sucursal (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.movimiento_inventario
    ADD CONSTRAINT movimiento_inventario_usuario_id_fkey FOREIGN KEY (usuario_id)
    REFERENCES public.usuario (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ordenes_compra
    ADD CONSTRAINT ordenes_compra_proveedor_id_fkey FOREIGN KEY (proveedor_id)
    REFERENCES public.proveedor (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ordenes_compra
    ADD CONSTRAINT ordenes_compra_resuelto_por_id_fkey FOREIGN KEY (resuelto_por_id)
    REFERENCES public.usuario (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ordenes_compra
    ADD CONSTRAINT ordenes_compra_sucursal_id_fkey FOREIGN KEY (sucursal_id)
    REFERENCES public.sucursal (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_orden_sucursal
    ON public.ordenes_compra(sucursal_id);


ALTER TABLE IF EXISTS public.ordenes_compra
    ADD CONSTRAINT ordenes_compra_usuario_id_fkey FOREIGN KEY (usuario_id)
    REFERENCES public.usuario (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ordenes_compra
    ADD CONSTRAINT ordenes_compra_usuario_recepcion_id_fkey FOREIGN KEY (usuario_recepcion_id)
    REFERENCES public.usuario (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.precio_por_lista
    ADD CONSTRAINT precio_por_lista_lista_id_fkey FOREIGN KEY (lista_id)
    REFERENCES public.lista_precios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.precio_por_lista
    ADD CONSTRAINT precio_por_lista_producto_id_fkey FOREIGN KEY (producto_id)
    REFERENCES public.producto (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.producto
    ADD CONSTRAINT fk_producto_unidad_medida FOREIGN KEY (unidad_id)
    REFERENCES public.unidad_medida (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.producto_proveedor
    ADD CONSTRAINT producto_proveedor_producto_id_fkey FOREIGN KEY (producto_id)
    REFERENCES public.producto (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.producto_proveedor
    ADD CONSTRAINT producto_proveedor_proveedor_id_fkey FOREIGN KEY (proveedor_id)
    REFERENCES public.proveedor (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.producto_unidad
    ADD CONSTRAINT producto_unidad_producto_id_fkey FOREIGN KEY (producto_id)
    REFERENCES public.producto (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.producto_unidad
    ADD CONSTRAINT producto_unidad_unidad_id_fkey FOREIGN KEY (unidad_id)
    REFERENCES public.unidad_medida (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.rutas_logisticas
    ADD CONSTRAINT rutas_logisticas_sucursal_destino_id_fkey FOREIGN KEY (sucursal_destino_id)
    REFERENCES public.sucursal (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.rutas_logisticas
    ADD CONSTRAINT rutas_logisticas_sucursal_origen_id_fkey FOREIGN KEY (sucursal_origen_id)
    REFERENCES public.sucursal (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.solicitudes_devolucion
    ADD CONSTRAINT solicitudes_devolucion_aprobador_id_fkey FOREIGN KEY (aprobador_id)
    REFERENCES public.usuario (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.solicitudes_devolucion
    ADD CONSTRAINT solicitudes_devolucion_solicitante_id_fkey FOREIGN KEY (solicitante_id)
    REFERENCES public.usuario (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.solicitudes_devolucion
    ADD CONSTRAINT solicitudes_devolucion_sucursal_id_fkey FOREIGN KEY (sucursal_id)
    REFERENCES public.sucursal (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_return_branch
    ON public.solicitudes_devolucion(sucursal_id);


ALTER TABLE IF EXISTS public.solicitudes_devolucion
    ADD CONSTRAINT solicitudes_devolucion_venta_id_fkey FOREIGN KEY (venta_id)
    REFERENCES public.ventas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_return_sale
    ON public.solicitudes_devolucion(venta_id);


ALTER TABLE IF EXISTS public.transferencias
    ADD CONSTRAINT transferencias_parent_transfer_id_fkey FOREIGN KEY (parent_transfer_id)
    REFERENCES public.transferencias (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.transferencias
    ADD CONSTRAINT transferencias_resuelto_por_id_fkey FOREIGN KEY (resuelto_por_id)
    REFERENCES public.usuario (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.transferencias
    ADD CONSTRAINT transferencias_sucursal_destino_id_fkey FOREIGN KEY (sucursal_destino_id)
    REFERENCES public.sucursal (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.transferencias
    ADD CONSTRAINT transferencias_sucursal_origen_id_fkey FOREIGN KEY (sucursal_origen_id)
    REFERENCES public.sucursal (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.usuario
    ADD CONSTRAINT usuario_rol_id_fkey FOREIGN KEY (rol_id)
    REFERENCES public.rol (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.usuario
    ADD CONSTRAINT usuario_sucursal_id_fkey FOREIGN KEY (sucursal_id)
    REFERENCES public.sucursal (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ventas
    ADD CONSTRAINT ventas_sucursal_id_fkey FOREIGN KEY (sucursal_id)
    REFERENCES public.sucursal (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_venta_sucursal
    ON public.ventas(sucursal_id);


ALTER TABLE IF EXISTS public.ventas
    ADD CONSTRAINT ventas_usuario_id_fkey FOREIGN KEY (usuario_id)
    REFERENCES public.usuario (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_venta_vendedor
    ON public.ventas(usuario_id);

END;